#ifndef STB_IMAGE_IMPLEMENTATION_H
#define STB_IMAGE_IMPLEMENTATION_H

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"
//定义宏STB_IMAGE_IMPLEMENTATION，让其只包含相关函数定义源码

#endif // STB_IMAGE_IMPLEMENTATION_H
